/**
 * Name Components - Database of names for generation
 * Used by app.js for smart name generation
 */

const nameComponents = {
    female: {
        prefixes: ['A','Al','Am','An','Ar','As','Au','Be','Br','Ca','Ce','Ch','Cl','Co','Cr','Da','De','Di','Do','E','El','Em','En','Er','Es','Ev','Fa','Fe','Fi','Fl','Ga','Ge','Gi','Gl','Gr','Ha','He','Hi','Ho','I','Is','J','Ja','Je','Jo','Ju','K','Ka','Ke','Ki','Ko','L','La','Le','Li','Lo','Lu','M','Ma','Me','Mi','Mo','N','Na','Ne','Ni','No','O','Ol','P','Pa','Pe','Ph','Pi','Po','R','Ra','Re','Rh','Ri','Ro','S','Sa','Se','Sh','Si','So','St','Su','T','Ta','Te','Th','Ti','To','U','V','Va','Ve','Vi','Vo','W','Wa','We','Wh','Wi','Wo','Y','Z'],
        roots: ['bella','lyn','rose','marie','anne','elle','ina','ette','ice','ity','ora','ara','ine','ise','ith','la','le','lia','lie','line','lise','lly','lyn','lynn','ma','me','mia','mie','mina','na','ne','nia','nie','nna','ra','re','ria','rie','rina','sa','se','sha','sia','sie','sina','ta','te','tia','tie','tina','va','ve','via','vie','vina','ya','ye','zia','zie'],
        suffixes: ['','a','e','i','o','y','ah','eh','ih','oh','uh','ala','ana','ara','ela','ena','era','ila','ina','ira','ola','ona','ora','ula','una','ura','ella','enna','erra','illa','inna','irra','olla','onna','orra','ulla','unna','urra','bella','belle','billy','cilla','cille','cilly','della','delle','dilly','ella','elle','elly'],
        classics: ['Elizabeth','Mary','Patricia','Jennifer','Linda','Barbara','Susan','Margaret','Dorothy','Lisa','Nancy','Karen','Betty','Helen','Sandra','Donna','Carol','Ruth','Sharon','Michelle','Laura','Sarah','Kimberly','Deborah','Jessica','Shirley','Cynthia','Angela','Melissa','Brenda','Amy','Rebecca','Virginia','Kathleen','Pamela','Martha','Debra','Amanda','Stephanie','Carolyn'],
        modern: ['Emma','Olivia','Ava','Isabella','Sophia','Mia','Charlotte','Amelia','Harper','Evelyn','Abigail','Emily','Ella','Madison','Scarlett','Grace','Chloe','Victoria','Riley','Aria','Layla','Lily','Aubrey','Penelope','Sofia','Camila','Skylar','Lucy','Paisley','Everly'],
        popular: ['Olivia','Emma','Charlotte','Amelia','Sophia','Isabella','Ava','Mia','Evelyn','Luna','Harper','Camila','Sofia','Scarlett','Elizabeth','Eleanor','Emily','Chloe','Mila','Violet','Penelope','Gianna','Aria','Abigail','Ella','Avery','Sofia','Elizabeth','Camila','Luna','Skyler','Nova','Isla','Aurora','Willow','Emilia','Stella','Zoey','Hazel','Ivy'],
        unique: ['Zephyra','Lyra','Isolde','Artemis','Calista','Dahlia','Elowen','Freya','Giselle','Heidi','Indigo','Josephine','Kinsley','Lucinda','Magnolia','Nala','Opaline','Poppy','Quinn','Raven','Sienna','Tatiana','Ursula','Valencia','Whitney','Ximena','Yara','Zara']
    },
    male: {
        prefixes: ['A','Al','Am','An','Ar','As','Au','Be','Br','Ca','Ce','Ch','Cl','Co','Cr','Da','De','Di','Do','E','El','Em','En','Er','Es','Ev','Fa','Fe','Fi','Fl','Ga','Ge','Gi','Gl','Gr','Ha','He','Hi','Ho','I','Is','J','Ja','Je','Jo','Ju','K','Ka','Ke','Ki','Ko','L','La','Le','Li','Lo','Lu','M','Ma','Me','Mi','Mo','N','Na','Ne','Ni','No','O','Ol','P','Pa','Pe','Ph','Pi','Po','R','Ra','Re','Rh','Ri','Ro','S','Sa','Se','Sh','Si','So','St','Su','T','Ta','Te','Th','Ti','To','U','V','Va','Ve','Vi','Vo','W','Wa','We','Wh','Wi','Wo','Y','Z'],
        roots: ['son','ton','don','ron','lon','mon','non','bon','con','fon','gon','hon','jon','kon','ard','ert','itt','old','ulf','win','wyn','bert','dred','fred','gard','hard','land','mond','nard','ward'],
        suffixes: ['','er','or','ar','en','in','on','un','an','yn','son','ton','don','ron','lon','mon','ard','ert','itt','old','ulf','win','wyn','bert','dred','fred','gard','hard','land','mond','nard','ward'],
        classics: ['James','John','Robert','Michael','William','David','Richard','Joseph','Thomas','Charles','Christopher','Daniel','Matthew','Anthony','Donald','Mark','Paul','Steven','Andrew','Kenneth','Joshua','Kevin','Brian','George','Edward','Ronald','Timothy','Jason','Jeffrey','Ryan'],
        modern: ['Liam','Noah','Oliver','James','Elijah','William','Henry','Lucas','Benjamin','Theodore','Mateo','Levi','Sebastian','Daniel','Jack','Michael','Alexander','Owen','Asher','Samuel','Ethan','Leo','Jackson','Mason','Ezra','John','Hudson','Luca','Aiden','Joseph'],
        popular: ['Liam','Noah','Oliver','James','Elijah','William','Henry','Lucas','Benjamin','Theodore','Mateo','Levi','Sebastian','Daniel','Jack','Michael','Alexander','Owen','Asher','Samuel','Ethan','Leo','Jackson','Mason','Ezra','John','Hudson','Luca','Aiden','Joseph','David','Wyatt','Julian','Grayson','Lincoln','Jaxon','Levi','Mateo','Jayden','Gabriel','Isaac','Anthony','Dylan','Luke','Maverick','Christopher','Josiah','Andrew','Theodore','Caleb','Ryan','Adrian','Miles','Eli','Nolan','Christian','Aaron','Cameron','Ezekiel','Colton','Luca','Landon','Hunter','Jonathan','Santiago','Axel','Easton','Cooper','Jeremiah','Angel','Roman','Connor','Jameson','Robert','Greyson','Jordan','Ian','Carson','Jaxson','Leonardo','Nicholas','Dominic','Austin','Everett','Brooks','Xavier','Kai','Jose','Parker','Adam','Jace','Wesley','Kayden','Silas','Bennett','Declan','Waylon','Weston','Evan','Emmett'],
        unique: ['Zephyr','Orion','Leandro','Kai','Atlas','Theron','Caspian','Declan','Ezekiel','Finnegan','Gavyn','Hector','Isiah','Jarrett','Kieran','Laurence','Maverick','Nicoli','Orson','Percival','Quincy','Ronan','Stellan','Talon','Ulysses','Valentin','Wyatt','Xander','Yusuf','Zeke']
    }
};
